### ISSUE TITLE
[EDIT] Add parameters to adherent

### ISSUE THREAD

**Issue by mickahell** [ESNFranceG33kTeam/sAPI#20]
# What is the expected enhancement?
Add @yoanpom feedback, we need to add "university" and "country" to adherent.

**Comment by yoanpom** [comment]
Autres champs à ajouter pour caractériser un·e adhérent·e :

- Comment il ou elle a entendu parler de nous (liste d'items prédéfinis)

- Est-ce que l'adhérent·e veut recevoir la newsletter (oui/non)

Et comme l'univ est sur une liste d'items prédéfinis, un champ texte 
libre "Précisions"

*Yoan Pompet*
Retrouvez moi aussi sur Linkedin <https://www.linkedin.com/in/ypompet/> 
et Twitter <https://twitter.com/YoanPom>
Le 28/08/2022 à 13:27, Michaël a écrit :

**Comment by mickahell** [comment]
> Autres champs à ajouter pour caractériser un·e adhérent·e : - Comment il ou elle a entendu parler de nous (liste d'items prédéfinis) - Est-ce que l'adhérent·e veut recevoir la newsletter (oui/non) Et comme l'univ est sur une liste d'items prédéfinis, un champ texte libre "Précisions" 

Ok, je vais aussi ajouter ces champs :
- speak_about
- newsletter

Pour les listes d'items, ca sera coté front.

**Comment by mickahell** [comment]
Recap des champs à ajouter :
- university
- homeland
- speak_about
- newsletter
